In [1]:
import numpy as np

arr = np.random.random((10,20,30,3))
print(arr)

[[[[0.68365634 0.16624922 0.00132535]
   [0.41463031 0.31319953 0.70832084]
   [0.1639106  0.43196337 0.68545319]
   ...
   [0.46348209 0.06460127 0.95527628]
   [0.61142024 0.65998332 0.27039292]
   [0.71009012 0.60593425 0.57891397]]

  [[0.95227987 0.08383849 0.15043006]
   [0.2156181  0.31202626 0.61767982]
   [0.70125515 0.91897096 0.85329217]
   ...
   [0.68675776 0.31990004 0.70238498]
   [0.77707751 0.94062174 0.31283154]
   [0.18182937 0.72801657 0.67587072]]

  [[0.46860672 0.89647687 0.37332974]
   [0.09391101 0.29930582 0.00739692]
   [0.11917238 0.68845873 0.88723122]
   ...
   [0.81594254 0.30430975 0.54375869]
   [0.88013975 0.86969911 0.05073403]
   [0.49672662 0.28766039 0.52410561]]

  ...

  [[0.53448615 0.63349938 0.67806336]
   [0.4031117  0.10979201 0.33234341]
   [0.62924915 0.45320042 0.49059969]
   ...
   [0.27708234 0.95138043 0.12692007]
   [0.73874986 0.87386848 0.37110256]
   [0.04639631 0.4984515  0.94719868]]

  [[0.82333508 0.0575466  0.21957415]
   [0.5